---
  - 
    magnetic_variation: "E000091 0106"
    code: 
      icao: "ENCN"
      iata: "KRS"
    elevation: 43
    name: "Kristiansand Lufthavn Kjevik"
    longitude: 8.08537
    location: 
      city: "Kjevik"
      country: "Norway"
    latitude: 58.2042
    id: 2456
  - 
    magnetic_variation: "E001226 0106"
    code: 
      icao: "ENGM"
      iata: "OSL"
    elevation: 689
    name: "Oslo Gardermoen"
    longitude: 11.1004
    location: 
      city: "Oslo"
      country: "Norway"
    latitude: 60.1939
    id: 2461
